"""Initial schema

Revision ID: 735c50e98ce0
Revises: 
Create Date: 2026-02-04 07:12:54.778836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735c50e98ce0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('last_gps_update', sa.DateTime(), nullable=True),
    sa.Column('work_start', sa.Time(), nullable=False),
    sa.Column('work_end', sa.Time(), nullable=False),
    sa.Column('max_visits_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_external_id'), 'agents', ['external_id'], unique=True)
    op.create_table('api_clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=8), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('max_points_per_request', sa.Integer(), nullable=False),
    sa.Column('monthly_quota', sa.Integer(), nullable=False),
    sa.Column('requests_this_month', sa.Integer(), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('allowed_regions', sa.JSON(), nullable=True),
    sa.Column('allowed_endpoints', sa.JSON(), nullable=True),
    sa.Column('ip_whitelist', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_clients_api_key_hash'), 'api_clients', ['api_key_hash'], unique=True)
    op.create_table('vehicles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_volume_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('height_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('length_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('width_m', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_refrigerated', sa.Boolean(), nullable=False),
    sa.Column('min_temp_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('max_temp_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('requires_loader', sa.Boolean(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=False),
    sa.Column('work_end', sa.Time(), nullable=False),
    sa.Column('cost_per_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fixed_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('driver_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('clients',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('category', sa.Enum('A', 'B', 'C', name='clientcategory'), nullable=False),
    sa.Column('visit_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('time_window_start', sa.Time(), nullable=False),
    sa.Column('time_window_end', sa.Time(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('outstanding_debt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_days_remaining', sa.Integer(), nullable=True),
    sa.Column('churn_risk_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('last_order_date', sa.Date(), nullable=True),
    sa.Column('is_new_client', sa.Boolean(), nullable=False),
    sa.Column('has_active_promo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_agent_id'), 'clients', ['agent_id'], unique=False)
    op.create_index(op.f('ix_clients_external_id'), 'clients', ['external_id'], unique=True)
    op.create_index(op.f('ix_clients_latitude'), 'clients', ['latitude'], unique=False)
    op.create_index(op.f('ix_clients_longitude'), 'clients', ['longitude'], unique=False)
    op.create_table('delivery_routes',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('route_date', sa.Date(), nullable=False),
    sa.Column('total_distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_stops', sa.Integer(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='routestatus'), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_routes_route_date'), 'delivery_routes', ['route_date'], unique=False)
    op.create_index(op.f('ix_delivery_routes_vehicle_id'), 'delivery_routes', ['vehicle_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DISPATCHER', 'AGENT', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('delivery_orders',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=True),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_time_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_TRANSIT', 'DELIVERED', 'FAILED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_orders_client_id'), 'delivery_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_delivery_orders_external_id'), 'delivery_orders', ['external_id'], unique=True)
    op.create_index(op.f('ix_delivery_orders_status'), 'delivery_orders', ['status'], unique=False)
    op.create_table('visit_plans',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('planned_time', sa.Time(), nullable=False),
    sa.Column('estimated_arrival_time', sa.Time(), nullable=True),
    sa.Column('estimated_departure_time', sa.Time(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('distance_from_previous_km', sa.Float(), nullable=True),
    sa.Column('duration_from_previous_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', 'CANCELLED', name='visitstatus'), nullable=False),
    sa.Column('actual_arrival_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'client_id', 'planned_date', name='uq_agent_client_date')
    )
    op.create_index(op.f('ix_visit_plans_agent_id'), 'visit_plans', ['agent_id'], unique=False)
    op.create_index(op.f('ix_visit_plans_client_id'), 'visit_plans', ['client_id'], unique=False)
    op.create_index(op.f('ix_visit_plans_planned_date'), 'visit_plans', ['planned_date'], unique=False)
    op.create_table('delivery_route_stops',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('distance_from_previous_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_from_previous_minutes', sa.Integer(), nullable=False),
    sa.Column('planned_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['delivery_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['delivery_routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_route_stops_order_id'), 'delivery_route_stops', ['order_id'], unique=False)
    op.create_index(op.f('ix_delivery_route_stops_route_id'), 'delivery_route_stops', ['route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_route_stops_route_id'), table_name='delivery_route_stops')
    op.drop_index(op.f('ix_delivery_route_stops_order_id'), table_name='delivery_route_stops')
    op.drop_table('delivery_route_stops')
    op.drop_index(op.f('ix_visit_plans_planned_date'), table_name='visit_plans')
    op.drop_index(op.f('ix_visit_plans_client_id'), table_name='visit_plans')
    op.drop_index(op.f('ix_visit_plans_agent_id'), table_name='visit_plans')
    op.drop_table('visit_plans')
    op.drop_index(op.f('ix_delivery_orders_status'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_external_id'), table_name='delivery_orders')
    op.drop_index(op.f('ix_delivery_orders_client_id'), table_name='delivery_orders')
    op.drop_table('delivery_orders')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_delivery_routes_vehicle_id'), table_name='delivery_routes')
    op.drop_index(op.f('ix_delivery_routes_route_date'), table_name='delivery_routes')
    op.drop_table('delivery_routes')
    op.drop_index(op.f('ix_clients_longitude'), table_name='clients')
    op.drop_index(op.f('ix_clients_latitude'), table_name='clients')
    op.drop_index(op.f('ix_clients_external_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_agent_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_api_clients_api_key_hash'), table_name='api_clients')
    op.drop_table('api_clients')
    op.drop_index(op.f('ix_agents_external_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
